Repository LikeLionSCH/9th_ASSIGNMENT, pull requests merged in 2021-05, with the labels that each got.

#36 Session01 HW - 배연주
  18_배연주/session01/join.css
  18_배연주/session01/join.html
  18_배연주/session01/youtube.jpg
Labels: Submit

#35 session01 assignment - 20_이예빈
  20_이예빈/README.md
  20_이예빈/session01/Membership Form.css
  20_이예빈/session01/Membership Form.html
  20_이예빈/session01/README.md
  20_이예빈/session01/Youtube Layout img.jpg
  20_이예빈/session01/Youtube Layout.xd
Labels: Submit

#37 레이아웃구성, 회원가입 폼 과제 제출 - 채희찬
  17_채희찬/20210428/join.css
  17_채희찬/20210428/join.html
  17_채희찬/20210428/youtube.jpg
Labels: Submit

#38 session01
  17_성현/session01/20175107/join.css
  17_성현/session01/20175107/join.html
  17_성현/session01/20175107/youtube.jpg.png
Labels: Submit

#41 HW_01
  19_송지영/2021-05-05/HW_01.jpg
  19_송지영/2021-05-05/join.css
  19_송지영/2021-05-05/join.html
Labels: Submit

#40 I'm YBS COME ON
  18_윤병수/20210428/Join_Membership.css
  18_윤병수/20210428/Join_Membership.html
  18_윤병수/20210428/Youtube_윤병수.PNG
Labels: Submit

#39 hw
  19_최연희/20210428/join.css
  19_최연희/20210428/join.html
  19_최연희/20210428/youtube.JPG
  19_최연희/readme.md
Labels: Submit

#42 html_css
  18_정은서/session01/join.css
  18_정은서/session01/join.html
  18_정은서/session01/youtube.PNG
Labels: ReSubmit

#45 박시연 20210428 과제 제출 (피드백 완료)
  18_박시연/20210428/join.css
  18_박시연/20210428/join.html
  18_박시연/20210428/youtube.jpg
Labels: ReSubmit

#53 session01 assignment - 19_최연희
  19_최연희/20210428/join.css
  19_최연희/20210428/join.html
Labels: ReSubmit

#50 session01 assignment-18_정은서
  18_정은서/session01/.vscode/settings.json
  18_정은서/session01/join.css
Labels: ReSubmit

#56 session02 assignment - 17_성현
  17_성현/session02/img/360도.jpg
  17_성현/session02/img/alt.jpg
  17_성현/session02/img/검색.png
  17_성현/session02/img/게임.jpg
  17_성현/session02/img/구독.png
  17_성현/session02/img/뉴스.jpg
  17_성현/session02/img/더보기.png
  17_성현/session02/img/로고.png
  17_성현/session02/img/로그인.png
  17_성현/session02/img/리스트.png
  17_성현/session02/img/보관함.png
  17_성현/session02/img/스포츠.jpg
  17_성현/session02/img/시청기록.png
  17_성현/session02/img/실시간.jpg
  17_성현/session02/img/영화.jpg
  17_성현/session02/img/음악.jpg
  17_성현/session02/img/채널 탐색.png
  17_성현/session02/img/추가.png
  17_성현/session02/img/키보드.png
  17_성현/session02/img/탐색.png
  17_성현/session02/img/학습.jpg
  17_성현/session02/img/홈.png
  17_성현/session02/youtube.css
  17_성현/session02/youtube.html
Labels: Submit

#54 session02 assignment-19_송지영
  19_송지영/2021-05-12/HW2.css
  19_송지영/2021-05-12/HW2.html
Labels: Submit

#57 Session02 assignment - 18_배연주
  18_배연주/session02/flexbox-froggy.png
  18_배연주/session02/image/account.png
  18_배연주/session02/image/compass.png
  18_배연주/session02/image/crown.png
  18_배연주/session02/image/gallery.png
  18_배연주/session02/image/game.png
  18_배연주/session02/image/home.png
  18_배연주/session02/image/keyboard.png
  18_배연주/session02/image/light-bulb.png
  18_배연주/session02/image/menu.png
  18_배연주/session02/image/menu2.png
  18_배연주/session02/image/menu3.png
  18_배연주/session02/image/music.png
  18_배연주/session02/image/news.png
  18_배연주/session02/image/past.png
  18_배연주/session02/image/play-button.png
  18_배연주/session02/image/search.png
  18_배연주/session02/image/video.png
  18_배연주/session02/image/virtual-reality.png
  18_배연주/session02/image/voice.png
  18_배연주/session02/image/wifi.png
  18_배연주/session02/image/youtube_logo.jpg
  18_배연주/session02/reset.css
  18_배연주/session02/youtube.css
  18_배연주/session02/youtube.html
  18_배연주/session03/01.py
  18_배연주/session03/02.py
  18_배연주/session03/03.py
  18_배연주/session03/04.py
  18_배연주/session03/05.py
Labels: ReSubmit

#59 session02 assignment - 19_최연희
  19_최연희/20210505/img/app.JPG
  19_최연희/20210505/img/home.JPG
  19_최연희/20210505/img/inform.JPG
  19_최연희/20210505/img/menu.jpg
  19_최연희/20210505/img/movie.JPG
  19_최연희/20210505/img/picture.JPG
  19_최연희/20210505/img/picture2.JPG
  19_최연희/20210505/img/record.JPG
  19_최연희/20210505/img/search.JPG
  19_최연희/20210505/img/storage.JPG
  19_최연희/20210505/img/subscribe.JPG
  19_최연희/20210505/img/user.jpg
  19_최연희/20210505/img/youtube.jpg
  19_최연희/20210505/reset.css
  19_최연희/20210505/youtube.css
  19_최연희/20210505/youtube.html
Labels: ReSubmit

#58 session02 assignment - 20_이예빈
  20_이예빈/session01/Membership Form.css
  20_이예빈/session02/Readme.md
  20_이예빈/session02/flexbox froggy 24 complete.PNG
  20_이예빈/session02/img/apps.PNG
  20_이예빈/session02/img/keyboard.PNG
  20_이예빈/session02/img/logo.PNG
  20_이예빈/session02/img/menu.PNG
  20_이예빈/session02/img/notice.PNG
  20_이예빈/session02/img/profile.PNG
  20_이예빈/session02/img/search.PNG
  20_이예빈/session02/img/upload.PNG
  20_이예빈/session02/img/구독.PNG
  20_이예빈/session02/img/나중에볼동영상.PNG
  20_이예빈/session02/img/내동영상.PNG
  20_이예빈/session02/img/더보기.PNG
  20_이예빈/session02/img/보관함.PNG
  20_이예빈/session02/img/시청기록.PNG
  20_이예빈/session02/img/음성검색.PNG
  20_이예빈/session02/img/좋아요표시한영상.PNG
  20_이예빈/session02/img/탐색.PNG
  20_이예빈/session02/img/홈.PNG
  20_이예빈/session02/youtube layout capture img/01 100 percent.PNG
  20_이예빈/session02/youtube layout capture img/01 125 percent.PNG
  20_이예빈/session02/youtube layout capture img/01 90 percent.PNG
  20_이예빈/session02/youtube layout capture img/100 percent.PNG
  20_이예빈/session02/youtube layout capture img/125 percent.PNG
  20_이예빈/session02/youtube layout capture img/200 percent.PNG
  20_이예빈/session02/youtube layout capture img/final 100 percent.PNG
  20_이예빈/session02/youtube layout capture img/final 150 percent.PNG
  20_이예빈/session02/youtube layout.css
  20_이예빈/session02/youtube layout.html
  20_이예빈/session02/youtube layout1.css
  20_이예빈/session02/youtube layout1.html
  20_이예빈/session02/youtube layout2.css
  20_이예빈/session02/youtube layout2.html
Labels: ReSubmit

#61 session02 assignment -18_정은서
  18_정은서/session02/flex_layout.css
  18_정은서/session02/flex_layout.html
  18_정은서/session02/header_icon.PNG
  18_정은서/session02/menu.svg
  18_정은서/session02/계정.PNG
  18_정은서/session02/상단우측메뉴.PNG
  18_정은서/session02/알림.PNG
  18_정은서/session02/영상녹화.PNG
  18_정은서/session02/음성검색.PNG
  18_정은서/session02/탐색.PNG
  18_정은서/session02/홈.PNG
Labels: ReSubmit

#65 session02 assignment - 18_윤병수
  18_윤병수/README.md
  18_윤병수/session01/Join_Membership.css
  18_윤병수/session01/Join_Membership.html
  18_윤병수/session01/Youtube_윤병수.PNG
  18_윤병수/session02/Youtube.css
  18_윤병수/session02/Youtube.html
  18_윤병수/session02/Youtube_Logo.png
  18_윤병수/session02/basic.png
  18_윤병수/session02/menu.svg
  18_윤병수/session02/개구리.PNG
  18_윤병수/session03/session03_HW01.py
  18_윤병수/session03/session03_HW02.py
  18_윤병수/session03/session03_HW03.py
  18_윤병수/session03/session03_HW04.py
  18_윤병수/session03/session03_HW05.py
Labels: ReSubmit

#63 session02 assignment - 19_허유빈
  19_허유빈/session01/join.html
  19_허유빈/session01/youtube.xd
  19_허유빈/session02/app-icon.png
  19_허유빈/session02/camcorder-icon.png
  19_허유빈/session02/home-icon.png
  19_허유빈/session02/mike-icon.png
  19_허유빈/session02/profile.png
  19_허유빈/session02/search-icon.png
  19_허유빈/session02/sidebar-icon.png
  19_허유빈/session02/video.png
  19_허유빈/session02/youtube-logo.png
  19_허유빈/session02/youtube.css
  19_허유빈/session02/youtube.html
  19_허유빈/session03/01.py
  19_허유빈/session03/02.py
  19_허유빈/session03/03.py
  19_허유빈/session03/04.py
  19_허유빈/session03/05.py
Labels: Submit

#71 session03 assignment - 19_허유빈
  19_허유빈/session03/04.py
Labels: ReSubmit

#62 session02 assignment - 17_채희찬
  17_채희찬/session1/join.css
  17_채희찬/session1/join.html
  17_채희찬/session1/youtube.jpg
  17_채희찬/session2/youtube.css
  17_채희찬/session2/youtube.html
  21_윤현지/session 2/FlexboxFroggy.png
Labels: ReSubmit

#64 session02 assignment - 18_박시연
  18_박시연/session01/20210428/join.css
  18_박시연/session01/20210428/join.html
  18_박시연/session01/20210428/youtube.jpg
  18_박시연/session02/font.css
  18_박시연/session02/img/channel_icon.png
  18_박시연/session02/img/divid_line.png
  18_박시연/session02/img/icon.png
  18_박시연/session02/img/live_streaming_icon.png
  18_박시연/session02/img/menu_icon.png
  18_박시연/session02/img/new_vid_upload_icon.png
  18_박시연/session02/img/search_icon.png
  18_박시연/session02/img/sidebar_icon.png
  18_박시연/session02/img/upload_icon.png
  18_박시연/session02/img/user_img.png
  18_박시연/session02/img/verification.png
  18_박시연/session02/img/video_thumbnail.png
  18_박시연/session02/img/voice_icon.png
  18_박시연/session02/img/white_icon.png
  18_박시연/session02/img/youtube_logo.png
  18_박시연/session02/youtube.css
  18_박시연/session02/youtube.html
Labels: ReSubmit

#68 session03 assignment - 20_이예빈
  20_이예빈/session03/1.py
  20_이예빈/session03/2.py
  20_이예빈/session03/3.py
  20_이예빈/session03/4.py
  20_이예빈/session03/5.py
  20_이예빈/session03/README.md
Labels: ReSubmit, Submit

#72 session 03 assignment - 17_채희찬
  17_채희찬/session3/code1.py
  17_채희찬/session3/code2.py
  17_채희찬/session3/code3.py
  17_채희찬/session3/code4.py
  17_채희찬/session3/code5.py
Labels: Submit

#73 session03 assignment - 17_성현
  17_성현/session03/session03-HW1.py
  17_성현/session03/session03-HW2.py
  17_성현/session03/session03-HW3.py
  17_성현/session03/session03-HW4.py
  17_성현/session03/session03-HW5.py
Labels: ReSubmit

#67 session03 assignment - 19_송지영
  19_송지영/2021-05-19/HW01.py
  19_송지영/2021-05-19/HW02.py
  19_송지영/2021-05-19/HW03.py
  19_송지영/2021-05-19/HW04.py
  19_송지영/2021-05-19/HW05.py
Labels: Submit

#70 session 02 assignment - 19_최연희
  19_최연희/20210505/youtube.css
  19_최연희/20210505/youtube.html
  19_최연희/session 03/Q_1.py
  19_최연희/session 03/Q_2.py
  19_최연희/session 03/Q_3.py
  19_최연희/session 03/Q_4.py
  19_최연희/session 03/Q_5.py
Labels: ReSubmit

#69 session02 assignment - 18_정은서
  18_정은서/session02/flex_layout.css
  18_정은서/session02/flex_layout.html
  18_정은서/session02/reset.css
  18_정은서/session03/1.py
  18_정은서/session03/2.py
  18_정은서/session03/3.py
  18_정은서/session03/4.py
  18_정은서/session03/5.py
Labels: ReSubmit, Submit

#78 session04 assignment - 17_성현
  17_성현/session04/session04-HW1.py
  17_성현/session04/session04-HW2.py
Labels: Submit

#82 API project
  .gitignore
  18_정은서/API/API.py
  18_정은서/session03/3.py
  18_정은서/session04/1.py
  18_정은서/session04/2.py
Labels: Submit

#76 session03 assignment - 18_박시연
  18_박시연/session03/.vscode/launch.json
  18_박시연/session03/1.py
  18_박시연/session03/2.py
  18_박시연/session03/3.py
  18_박시연/session03/4.py
  18_박시연/session03/5.py
  18_박시연/session04/1.py
  18_박시연/session04/2.py
Labels: Submit

#60 session04 assignment - 18_이민수
  18_이민수/20210428/join.css
  18_이민수/20210505/index.css
  18_이민수/20210505/index.html
  18_이민수/20210512/1.py
  18_이민수/20210512/2.py
  18_이민수/20210512/3.py
  18_이민수/20210512/4.py
  18_이민수/20210512/5.py
  18_이민수/20210519/assignment_1.py
  18_이민수/20210519/assignment_2.py
  18_이민수/api_practice/.gitignore
  18_이민수/api_practice/ow.py
Labels: Submit

#86 session04 assignment - 19_허유빈
  19_허유빈/session04/01.py
  19_허유빈/session04/02.py
Labels: Submit

#80 session04 assignment - 20_이예빈
  20_이예빈/session04/1.py
  20_이예빈/session04/2.py
  20_이예빈/session04/README.md
Labels: Submit

#89 session05 assignment - 19_허유빈
  19_허유빈/session04/02.py
  19_허유빈/session05/01.py
Labels: Submit
