Repository LikeLionSCH/9th_ASSIGNMENT, pull requests merged in 2021-06, with the labels that each got.

#2 session06 assignment - 17_성현
  17_성현/session06/templates/count.html
  17_성현/session06/templates/home.html
  17_성현/session06/templates/result.html
  17_성현/session06/templates/test.html
  17_성현/session06/templates/test1.html
  17_성현/session06/templates/test2.html
  17_성현/session06/urls.py
  17_성현/session06/views.py
  17_성현/session06/실행 화면.png
Labels: submit

#4 session06 assignment - 18_윤병수
  18_윤병수/session06/count.html
  18_윤병수/session06/result.html
  18_윤병수/session06/test.html
  18_윤병수/session06/test1.html
  18_윤병수/session06/test2.html
  18_윤병수/session06/urls.py
  18_윤병수/session06/views.py
Labels: submit

#6 session06 assignment 19-송지영
  19_송지영/session06/session06.PNG
Labels: resubmit

#7 session04 assignment - 18_윤병수
  18_윤병수/session04/Change.py
  18_윤병수/session04/practice.py
Labels: submit

#8 session06 assignment - 18_배연주
  18_배연주/session06/test/test.html.png
  18_배연주/session06/test/test1.html.png
  18_배연주/session06/test/test2.html.png
  18_배연주/session06/test/urls.py.png
  18_배연주/session06/test/views.py.png
  18_배연주/session06/test/실행화면.png
  18_배연주/session06/wordCount/count 실행화면.png
  18_배연주/session06/wordCount/count.html.png
  18_배연주/session06/wordCount/result 실행화면.png
  18_배연주/session06/wordCount/result.html.png
  18_배연주/session06/wordCount/urls.py.png
  18_배연주/session06/wordCount/views.py.png
Labels: submit

#12 session06 assignment - 17_채희찬
  17_채희찬/session6/count.html
  17_채희찬/session6/count.html 캡쳐.PNG
  17_채희찬/session6/resukt.html 캡쳐.PNG
  17_채희찬/session6/result.html
  17_채희찬/session6/test.html
  17_채희찬/session6/test.html 캡쳐.PNG
  17_채희찬/session6/test1.html
  17_채희찬/session6/test1.html 캡쳐.PNG
  17_채희찬/session6/test2.html
  17_채희찬/session6/test2.html 캡쳐.PNG
  17_채희찬/session6/urls.py
  17_채희찬/session6/urls.py 캡쳐.PNG
  17_채희찬/session6/views.py
  17_채희찬/session6/views.py 캡쳐.PNG
  17_채희찬/session6/실행결과.PNG
Labels: submit

#11 session06 assignment - 19_허유빈
  19_허유빈/session06/count 실행화면.png
  19_허유빈/session06/count.html
  19_허유빈/session06/result 실행화면.png
  19_허유빈/session06/result.html
  19_허유빈/session06/test 실행화면.png
  19_허유빈/session06/test.html
  19_허유빈/session06/test1 실행화면.png
  19_허유빈/session06/test1.html
  19_허유빈/session06/test2 실행화면.png
  19_허유빈/session06/test2.html
  19_허유빈/session06/urls.py
  19_허유빈/session06/views.py
Labels: submit

#16 session05 assignment - 18_윤병수
  18_윤병수/session_05/hw_1.py
  19_허유빈/session05/01.py
Labels: submit

#19 session06 assignment_ 18-정은서
  18_정은서/session06/templates/count.html
  18_정은서/session06/templates/home.html
  18_정은서/session06/templates/result.html
  18_정은서/session06/templates/test.html
  18_정은서/session06/templates/test1.html
  18_정은서/session06/templates/test2.html
  18_정은서/session06/urls.py
  18_정은서/session06/views.py
  18_정은서/session06/실행결과캡쳐.PNG
Labels: submit

#9 session06 assignment - 19_최연희
  19_최연희/session 06/.gitignore
  19_최연희/session 06/html/count.html
  19_최연희/session 06/html/home.html
  19_최연희/session 06/html/result.html
  19_최연희/session 06/html/test.html
  19_최연희/session 06/html/test1.html
  19_최연희/session 06/html/test2.html
  19_최연희/session 06/img/1.JPG
  19_최연희/session 06/img/2.JPG
  19_최연희/session 06/img/3.JPG
  19_최연희/session 06/img/4.JPG
  19_최연희/session 06/img/5.JPG
  19_최연희/session 06/img/6.JPG
  19_최연희/session 06/urls.py
  19_최연희/session 06/views.py
Labels: submit

#22 session06 assignment - 18_이민수
  18_이민수/20210618/result.html
  18_이민수/20210618/urls.py
  18_이민수/20210618/views.py
  18_이민수/20210618/실행결과.PNG
Labels: submit

#18 session07 assignment - 21_윤현지
  21_윤현지/session06/count.html
  21_윤현지/session06/result.html
  21_윤현지/session06/session06 결과 1.png
  21_윤현지/session06/session06 결과 2.png
  21_윤현지/session06/test.html
  21_윤현지/session06/test1.html
  21_윤현지/session06/test2.html
  21_윤현지/session06/urls.py
  21_윤현지/session06/views.py
  21_윤현지/session07/admin.py
  21_윤현지/session07/base.html
  21_윤현지/session07/haha.html
  21_윤현지/session07/home.html
  21_윤현지/session07/models.py
  21_윤현지/session07/session07 결과 1.png
  21_윤현지/session07/session07 결과 2.png
  21_윤현지/session07/urls.py
  21_윤현지/session07/views.py
Labels: resubmit, submit

#29 session07 assignment-21_윤현지
  21_윤현지/session07/admin.py
  21_윤현지/session07/base.html
  21_윤현지/session07/haha.html
  21_윤현지/session07/home.html
  21_윤현지/session07/models.py
  21_윤현지/session07/urls.py
  21_윤현지/session07/views.py
  21_윤현지/session07/결과 1.png
  21_윤현지/session07/결과 2.png
Labels: resubmit

#26 session07 assignment - 19_최연희
  19_최연희/session 07/.gitignore
  19_최연희/session 07/html/base.html
  19_최연희/session 07/html/dog.html
  19_최연희/session 07/html/home.html
  19_최연희/session 07/img/1.JPG
  19_최연희/session 07/img/2.JPG
  19_최연희/session 07/urls.py
  19_최연희/session 07/views.py
Labels: submit

#10 session06 assignment - 18_박시연
  18_박시연/session05/homework.py
  18_박시연/session06/apps.py
  18_박시연/session06/count.png
  18_박시연/session06/result.png
  18_박시연/session06/settings.py
  18_박시연/session06/templates/count.html
  18_박시연/session06/templates/result.html
  18_박시연/session06/templates/test.html
  18_박시연/session06/templates/test1.html
  18_박시연/session06/templates/test2.html
  18_박시연/session06/test.png
  18_박시연/session06/test1.png
  18_박시연/session06/test2.png
  18_박시연/session06/urls.py
  18_박시연/session06/views.py
Labels: submit

#28 session07 assignment - 18_정은서
  18_정은서/session08/catproject/cat/__init__.py
  18_정은서/session08/catproject/cat/__pycache__/__init__.cpython-39.pyc
  18_정은서/session08/catproject/cat/__pycache__/admin.cpython-39.pyc
  18_정은서/session08/catproject/cat/__pycache__/apps.cpython-39.pyc
  18_정은서/session08/catproject/cat/__pycache__/models.cpython-39.pyc
  18_정은서/session08/catproject/cat/__pycache__/views.cpython-39.pyc
  18_정은서/session08/catproject/cat/admin.py
  18_정은서/session08/catproject/cat/apps.py
  18_정은서/session08/catproject/cat/migrations/0001_initial.py
  18_정은서/session08/catproject/cat/migrations/__init__.py
  18_정은서/session08/catproject/cat/migrations/__pycache__/0001_initial.cpython-39.pyc
  18_정은서/session08/catproject/cat/migrations/__pycache__/__init__.cpython-39.pyc
  18_정은서/session08/catproject/cat/models.py
  18_정은서/session08/catproject/cat/static/css/home.css
  18_정은서/session08/catproject/cat/templates/base.html
  18_정은서/session08/catproject/cat/templates/detail.html
  18_정은서/session08/catproject/cat/templates/edit.html
  18_정은서/session08/catproject/cat/templates/home.html
  18_정은서/session08/catproject/cat/templates/new.html
  18_정은서/session08/catproject/cat/tests.py
  18_정은서/session08/catproject/cat/views.py
  18_정은서/session08/catproject/catproject/__init__.py
  18_정은서/session08/catproject/catproject/__pycache__/__init__.cpython-39.pyc
  18_정은서/session08/catproject/catproject/__pycache__/settings.cpython-39.pyc
  18_정은서/session08/catproject/catproject/__pycache__/urls.cpython-39.pyc
  18_정은서/session08/catproject/catproject/__pycache__/wsgi.cpython-39.pyc
  18_정은서/session08/catproject/catproject/asgi.py
  18_정은서/session08/catproject/catproject/settings.py
  18_정은서/session08/catproject/catproject/urls.py
  18_정은서/session08/catproject/catproject/wsgi.py
  18_정은서/session08/catproject/db.sqlite3
  18_정은서/session08/catproject/manage.py
  18_정은서/session08/catproject/media/cat/KakaoTalk_20210629_104042217.jpg
  18_정은서/session08/catproject/media/cat/mango.jpg
  18_정은서/session08/catproject/media/cat/우분투에러20181491정은서.PNG
  18_정은서/session08/session8 실습결과.PNG
  18_정은서/sessoion07/blog/__pycache__/__init__.cpython-39.pyc
  18_정은서/sessoion07/blog/__pycache__/admin.cpython-39.pyc
  18_정은서/sessoion07/blog/__pycache__/apps.cpython-39.pyc
  18_정은서/sessoion07/blog/__pycache__/models.cpython-39.pyc
  18_정은서/sessoion07/blog/__pycache__/views.cpython-39.pyc
  18_정은서/sessoion07/blog/migrations/__pycache__/0001_initial.cpython-39.pyc
  18_정은서/sessoion07/blog/migrations/__pycache__/__init__.cpython-39.pyc
  18_정은서/sessoion07/blog/models.py
  18_정은서/sessoion07/blog/static/css/cat.css
  18_정은서/sessoion07/blog/templates/cat.html
  18_정은서/sessoion07/blog/views.py
  18_정은서/sessoion07/blog/줌배경.jpg
  18_정은서/sessoion07/blogproject/__pycache__/__init__.cpython-39.pyc
  18_정은서/sessoion07/blogproject/__pycache__/settings.cpython-39.pyc
  18_정은서/sessoion07/blogproject/__pycache__/wsgi.cpython-39.pyc
  18_정은서/sessoion07/실행결과_cat.PNG
  18_정은서/sessoion07/실행결과_home.PNG
  gitignore.txt
Labels: resubmit

#30 session07 assignment - 17_채희찬
  17_채희찬/session7/base.html
  17_채희찬/session7/cat.css
  17_채희찬/session7/cat.html
  17_채희찬/session7/home.css
  17_채희찬/session7/home.html
  17_채희찬/session7/urls.py
  17_채희찬/session7/views.py
  17_채희찬/session7/고양이 실행화면.PNG
  17_채희찬/session7/홈 실행화면.PNG
Labels: submit
